### ISSUE TITLE
How to compile this project?

### ISSUE THREAD

**Issue by facha** [rbheemana/Cobol-to-Hive#20]
Hello,

Could you provide instructions on how to build a serde jar from source?

Thanks in advance.

**Comment by rbheemana** [comment]
you can generate CobolSerde.jar by yourself on the cluster with something like ( I prefer this approach since we can avoid version discrepancies)

Cobol-to-Hive-master\src>set %classpath%=%HADOOP_HOME%\*;%HIVE_HOME%\lib\*;
Cobol-to-Hive-master\src>javac com\savy3\hadoop\hive\serde2\cobol\*.java
Cobol-to-Hive-master\src>javac com\savy3\hadoop\hive\serde3\cobol\*.java
Cobol-to-Hive-master\src>javac com\savy3\mapred\*.java
Cobol-to-Hive-master\src>javac com\savy3\mapreduce\*.java
Cobol-to-Hive-master\src>jar cf CobolSerde_v030817.jar com
Cobol-to-Hive-master\src>jar tf CobolSerde_v030817.jar

I have added Pom file through which u can compile but I does not have dependencies for utilities package.

Hope this helps
